version: '3.9'

services:
  authservice:
    build:
      context: .
      dockerfile: AuthService.NET/Dockerfile
    container_name: authservice.api
    depends_on:
        - postgres
    environment:
    - ASPNEFCORE_ENVIRONMENT=Development
    - ConnectionStrings_Default=Host=postgres;Port=5432;Database=authdb;Username=authuser;Password=authpassword
    ports:
    - "5000:8080"
    - "5001:8081"
    restart: always

  postgres:
    image: postgres:15
    container_name: authservice.db
    environment:
        POSTGRES_DB: authdb
        POSTGRES_USER: authuser
        POSTGRES_PASSWORD: authpassword
    ports:
        - "5432:5432"
    volumes:
        - postgres_data:/var/lib/postgresql/data
volumes:
    postgres_data: